import type { Metadata } from 'next';
import { Geist, Geist_Mono, Kavivanar } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const kavivanar = Kavivanar({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-kavivanar',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${kavivanar.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
